# Example wx-uploader configuration file
# This file supports multiple WeChat public accounts and centralized settings

# WeChat accounts configuration
accounts:
  personal:
    name: personal
    app_id: your_personal_app_id_here
    app_secret: your_personal_app_secret_here
    description: Personal WeChat public account
    
  work:
    name: work
    app_id: your_work_app_id_here
    app_secret: your_work_app_secret_here
    description: Work WeChat public account
    
  blog:
    name: blog
    app_id: your_blog_app_id_here
    app_secret: your_blog_app_secret_here
    description: Technical blog WeChat account

# Default account to use when no account is specified
default_account: personal

# AI provider configuration for cover image generation
ai_provider:
  provider: openai  # Options: openai, gemini
  api_key: your_openai_api_key_here
  # base_url: https://api.openai.com/v1  # Optional: custom base URL

# Global settings
settings:
  verbose: false
  default_theme: lapis  # Theme for WeChat articles
  default_code_highlighter: github  # Code syntax highlighter